[package]
name = "untitled"
version = "0.1.0"
authors = ["Nikolas Virostek <virostek@metaapp.sk>"]
edition = "2018"

[dependencies]
raft = { git = "https://github.com/pingcap/raft-rs.git" }
prost = "0.5"
regex = "1.1"
env_logger = "0.5"
log = ">0.2"
protobuf = "~2.1-2.2"
bincode = "1.1.3"
serde_derive = "1.0.34"
serde = "1.0.34"